# Generated by Django 2.2.6 on 2019-10-20 04:49

import autho.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('slug', models.SlugField(default=autho.models.generateUUID, unique=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('manuscript', models.CharField(blank=True, max_length=500, null=True)),
                ('speech2text', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
