# Generated by Django 2.2.6 on 2019-10-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='filler_per',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='speech',
            name='gaze_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='speech',
            name='generated_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='text_sim',
            field=models.FloatField(default=0.0),
        ),
    ]
