# Generated by Django 2.2.6 on 2019-10-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0002_auto_20191020_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='id',
        ),
        migrations.AddField(
            model_name='speech',
            name='speech_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
