# Generated by Django 2.2.6 on 2019-10-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0002_auto_20191020_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='speech2text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
